spring:
  application:
    name: consumer-demo

server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000