spring:
  application:
    name: consumer-demo-feign

server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
